### PR TITLE
Integrational Tests

### PR DESCRIPTION
**Pull request by ngoquang2708**
Where should we place ```.env``` and ```docker-compose.yaml``` file for tests?

### CODE REVIEW

**Comment by red-avtovo** [comment]
Please put them under `env-test` directory

**Comment by ngoquang2708** [comment]
If we move ```.env``` to ```env-test``` then ```dotenv()``` cannot read it?

**Comment by red-avtovo** [comment]
Yeah, makes sense. Then put everything in the repo root

**Comment by ngoquang2708** [comment]
All tests passed. Please review.

**Comment by red-avtovo** [comment]
That looks amazing! Thank you so much for bringing that
Fixes #32

**Pull request merged**
