### PR TITLE
Add support for doneDate Torrent field

### LINKED ISSUE #40: Add the "done date" on torrent info?
I'm really interested in the [`doneDate`](https://github.com/transmission/transmission/blob/cc4cf1da5a68bf4e20f82e97e7dbd4babfad3da1/extras/rpc-spec.txt#L201) on a `Torrent` structure. It indicates the time at which a download finished & turned into "Seeding". 

Is it possible to add this field?

### PR DESCRIPTION
**Pull request by antifuchs**
This fixes #40 - it was easier to write myself than bother you.

I notice that these dates are all in `i64` representation. Together with [chrono](https://docs.rs/chrono/0.4.19/chrono/serde/index.html), these could be decoded into real datetimes. Would you be interested in a patch like that?

### CODE REVIEW

**Comment by red-avtovo** [comment]
Hi @antifuchs!
Thank you so much for your interest in this library and especially your contribution 🎉 
I totally see sense in your proposal

**Comment by red-avtovo** [comment]
Can you also please update examples?

**Comment by antifuchs** [comment]
Yup, will do when I get home!

**Comment by red-avtovo** [comment]
Cheers!

**Comment by antifuchs** [comment]
I looked into adding something to examples, but I'm not sure where the field would fit best. `examples/torrent_get.rs`, maybe? Did you have a specific one in mind?

**Review by red-avtovo — APPROVED** [review]

**Comment by red-avtovo** [comment]
I double-checked examples and they are all good. Apologies for not responding for so long

**Pull request merged**
